import type { Metadata } from "next";
import { Inter, Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";

const rubik = Rubik({subsets: ["latin"], weight: ["400", "700"]})
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "School",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
